// 语数外学习卡牌系统: 20 cards per subject + 1 UR limited card (61 total).
// Fields: id, subj (YW 语文 / SX 数学 / YY 英语 / UR), rarity, name, art (emoji stand-in for the front image),
// know (📖 知识点), task (✏️ 小任务), tip (💡 小贴士)
window.CARDS = [
  // ---------------- 语文 · 字词句篇，步步积累 ----------------
  { id: 'YW-01', subj: 'YW', rarity: 'N', name: '拼音小兵', art: '💂🔤', know: '声母23个，韵母24个，整体认读音节16个', task: '正确拼读10个音节', tip: 'b-p、d-t 要分清，送气不送气摸纸条' },
  { id: 'YW-02', subj: 'YW', rarity: 'N', name: '偏旁卫士', art: '🛡️氵', know: '常见偏旁表义规律（氵与水有关，木与树有关）', task: '说出5个同偏旁的字', tip: '偏旁是汉字的"家族徽章"' },
  { id: 'YW-03', subj: 'YW', rarity: 'N', name: '笔画达人', art: '🖌️丿', know: '基本笔画8种：横、竖、撇、捺、点、提、折、钩', task: '正确书写5个易错字', tip: '先横后竖，先撇后捺，从上到下，从左到右' },
  { id: 'YW-04', subj: 'YW', rarity: 'N', name: '词语接龙', art: '🐉🀄', know: '词语接龙规则：下一个词的首字=上一个词的尾字', task: '完成一次词语接龙', tip: '平时多积累，接龙不卡壳' },
  { id: 'YW-05', subj: 'YW', rarity: 'N', name: '造句新手', art: '🧒🪧', know: '完整句子=谁+在哪里+做什么', task: '用指定词造一个完整句子', tip: '句子要通顺，标点不能忘' },
  { id: 'YW-06', subj: 'YW', rarity: 'N', name: '标点小警', art: '👮❓', know: '常用标点：。，、？！：；""\'\'', task: '给一段话加上正确标点', tip: '句号说完一句话，问号表示有疑问' },
  { id: 'YW-07', subj: 'YW', rarity: 'N', name: '朗读之星', art: '📖🎵', know: '朗读三要素：正确、流利、有感情', task: '有声朗读一段课文', tip: '朗读时注意停顿和语气' },
  { id: 'YW-08', subj: 'YW', rarity: 'N', name: '听写能手', art: '👂✏️', know: '听写技巧：先听清，再动笔，写完检查', task: '听写全对', tip: '易错字要多写几遍' },
  { id: 'YW-09', subj: 'YW', rarity: 'R', name: '成语侦探', art: '🕵️📜', know: '成语四字为主，多来自历史故事或寓言', task: '积累5个新成语并理解意思', tip: '成语要连意思一起记，不能只背字' },
  { id: 'YW-10', subj: 'YW', rarity: 'R', name: '古诗传人', art: '🌙🧙', know: '古诗分类：五言/七言，绝句/律诗', task: '背诵一首新古诗', tip: '先理解意思，再背诵，记得更牢' },
  { id: 'YW-11', subj: 'YW', rarity: 'R', name: '阅读行者', art: '🎒📚', know: '阅读三问：谁？做了什么？结果怎样？', task: '读完一本课外书并复述', tip: '每天读15分钟，一年能读很多本' },
  { id: 'YW-12', subj: 'YW', rarity: 'R', name: '修辞法师', art: '🪄✨', know: '比喻=把甲比作乙；拟人=把物当人写', task: '识别并仿写比喻/拟人句', tip: '本体和喻体要有相似点' },
  { id: 'YW-13', subj: 'YW', rarity: 'R', name: '日记作家', art: '📔🖋️', know: '日记格式：日期、星期、天气、正文', task: '坚持写日记一周', tip: '写真实的事，哪怕只有三句话' },
  { id: 'YW-14', subj: 'YW', rarity: 'R', name: '修改大师', art: '👩‍🏫🖍️', know: '常见语病：成分残缺、搭配不当、前后矛盾', task: '修改一段有语病的文字', tip: '读一遍，不通顺的地方就是问题' },
  { id: 'YW-15', subj: 'YW', rarity: 'SR', name: '古文初探', art: '🎋🔍', know: '小古文常见词：之、其、而、以、于', task: '理解一篇小古文并翻译', tip: '先猜大意，再查字词，最后连起来' },
  { id: 'YW-16', subj: 'YW', rarity: 'SR', name: '作文新星', art: '🌟📝', know: '作文结构：开头点题、中间具体、结尾升华', task: '完成一篇优秀作文', tip: '写前先列提纲，写后读一遍' },
  { id: 'YW-17', subj: 'YW', rarity: 'SR', name: '诗词达人', art: '📖🌸', know: '古诗常见意象：月=思乡，柳=送别，梅=高洁', task: '连续背诵10首古诗', tip: '按主题分类背，更容易记住' },
  { id: 'YW-18', subj: 'YW', rarity: 'SR', name: '阅读王者', art: '👑📚', know: '精读方法：圈点批注、摘抄好句、写读后感', task: '一个月读完3本书并做笔记', tip: '读书笔记不用长，一句话也行' },
  { id: 'YW-19', subj: 'YW', rarity: 'SSR', name: '语文宗师', art: '🧓📜', know: '语文综合能力：字词句篇、听说读写', task: '期中/期末语文成绩优异', tip: '语文靠积累，每天进步一点点' },
  { id: 'YW-20', subj: 'YW', rarity: 'SSR', name: '文曲星下凡', art: '🌠🖌️', know: '语文竞赛常见题型：基础知识、阅读理解、写作', task: '校级语文竞赛获奖', tip: '竞赛前多练真题，沉着应战' },

  // ---------------- 数学 · 数形结合，逻辑闯关 ----------------
  { id: 'SX-01', subj: 'SX', rarity: 'N', name: '口算小兵', art: '🪖🔢', know: '20以内加减法口算技巧：凑十法、破十法', task: '20以内口算全对', tip: '每天练5分钟，速度自然快' },
  { id: 'SX-02', subj: 'SX', rarity: 'N', name: '数位卫士', art: '💂💂💂', know: '数位顺序：个、十、百、千、万', task: '正确读写万以内数', tip: '读数从高位起，写数从高位起' },
  { id: 'SX-03', subj: 'SX', rarity: 'N', name: '图形侦探', art: '🔍🔺', know: '基本图形：圆、三角形、正方形、长方形、平行四边形', task: '认出5种基本图形', tip: '生活中到处是图形，找找看' },
  { id: 'SX-04', subj: 'SX', rarity: 'N', name: '单位达人', art: '📏⚖️⏰', know: '长度单位：毫米、厘米、分米、米、千米', task: '正确使用长度/质量单位', tip: '1米=100厘米，1千克=1000克' },
  { id: 'SX-05', subj: 'SX', rarity: 'N', name: '时钟管家', art: '🕰️', know: '时针走一大格=1小时，分针走一小格=1分钟', task: '正确认读时间', tip: '先看时针，再看分针' },
  { id: 'SX-06', subj: 'SX', rarity: 'N', name: '加减新手', art: '➕🤝➖', know: '加法=合并，减法=去掉', task: '完成10道加减法', tip: '加法想凑十，减法想破十' },
  { id: 'SX-07', subj: 'SX', rarity: 'N', name: '乘法口诀', art: '✖️🪜', know: '乘法口诀表，从一一得一到九九八十一', task: '背出指定口诀', tip: '横着背、竖着背、打乱背' },
  { id: 'SX-08', subj: 'SX', rarity: 'N', name: '估算小能', art: '🛒💭', know: '估算方法：四舍五入、凑整', task: '完成一次合理估算', tip: '估算不是精确计算，快速判断即可' },
  { id: 'SX-09', subj: 'SX', rarity: 'R', name: '应用题破', art: '🧩', know: '应用题三步：读题、找条件、列式', task: '独立解出2道应用题', tip: '圈出关键词，排除多余信息' },
  { id: 'SX-10', subj: 'SX', rarity: 'R', name: '竖式高手', art: '🧮', know: '竖式加减法：相同数位对齐，从个位算起', task: '竖式计算全对', tip: '进位别忘了加，退位别忘了减' },
  { id: 'SX-11', subj: 'SX', rarity: 'R', name: '分数初探', art: '🍕½', know: '分数=把整体平均分，取其中几份', task: '理解并比较简单分数', tip: '分母越大，每份越小' },
  { id: 'SX-12', subj: 'SX', rarity: 'R', name: '周长专家', art: '⬜📏', know: '周长=图形一周的长度', task: '计算图形周长', tip: '长方形周长=（长+宽）×2' },
  { id: 'SX-13', subj: 'SX', rarity: 'R', name: '统计小员', art: '📊🥧', know: '统计图类型：条形图、折线图、扇形图', task: '完成一次数据统计图', tip: '条形图看多少，折线图看变化' },
  { id: 'SX-14', subj: 'SX', rarity: 'R', name: '找规律王', art: '🔴🔵🔴', know: '常见规律：等差、等比、循环', task: '找出数列规律并续写', tip: '先看相邻两数差多少' },
  { id: 'SX-15', subj: 'SX', rarity: 'SR', name: '面积大师', art: '🟩📐', know: '面积=物体表面的大小', task: '计算组合图形面积', tip: '组合图形可以分割或补全' },
  { id: 'SX-16', subj: 'SX', rarity: 'SR', name: '方程先锋', art: '⚖️x', know: '方程=含有未知数的等式', task: '解简单方程', tip: '等式两边同时加减乘除同一个数' },
  { id: 'SX-17', subj: 'SX', rarity: 'SR', name: '几何智者', art: '🧙📐', know: '三角形内角和=180°，四边形内角和=360°', task: '完成一道几何证明/推理', tip: '画图帮助理解，标注已知条件' },
  { id: 'SX-18', subj: 'SX', rarity: 'SR', name: '速算王者', art: '👑➗', know: '速算技巧：凑整、分配律、结合律', task: '限时口算全对', tip: '先观察，再计算，能简算就简算' },
  { id: 'SX-19', subj: 'SX', rarity: 'SSR', name: '数学宗师', art: '👨‍🔬∑', know: '数学综合能力：数感、运算、几何、统计', task: '期中/期末数学成绩优异', tip: '数学靠理解，不是靠死记' },
  { id: 'SX-20', subj: 'SX', rarity: 'SSR', name: '华罗庚传人', art: '🎓π', know: '数学竞赛常见题型：巧算、逻辑推理、几何', task: '校级数学竞赛获奖', tip: '多动笔，多思考，不怕难题' },

  // ---------------- 英语 · 听说读写，开口即赢 ----------------
  { id: 'YY-01', subj: 'YY', rarity: 'N', name: '字母小兵', art: '💂🔠', know: '26个字母大小写：Aa-Zz', task: '正确认读26个字母', tip: '字母歌帮助记忆顺序' },
  { id: 'YY-02', subj: 'YY', rarity: 'N', name: '音标卫士', art: '🛡️/æ/', know: '元音20个，辅音28个', task: '正确拼读5个音标', tip: '元音要饱满，辅音要轻短' },
  { id: 'YY-03', subj: 'YY', rarity: 'N', name: '单词新手', art: '🧒📓', know: '单词记忆法：自然拼读、联想、分类', task: '记住5个新单词', tip: '单词放到句子里记，更牢固' },
  { id: 'YY-04', subj: 'YY', rarity: 'N', name: '颜色达人', art: '🌈🎨', know: 'red, orange, yellow, green, blue, purple', task: '说出5种颜色英文', tip: '看到颜色就说英文，随时练习' },
  { id: 'YY-05', subj: 'YY', rarity: 'N', name: '数字能手', art: '1️⃣2️⃣0️⃣', know: 'one, two, three... twenty', task: '用英语数1-20', tip: 'thirteen和thirty要区分' },
  { id: 'YY-06', subj: 'YY', rarity: 'N', name: '问候之星', art: '👋🧒', know: 'Hello! Hi! Good morning! How are you?', task: '用英语打招呼对话', tip: '见到老师同学，大胆开口' },
  { id: 'YY-07', subj: 'YY', rarity: 'N', name: '书写小警', art: '👮Aa', know: '字母书写规范：占格、笔顺、大小写', task: '正确书写5个单词', tip: '字母要写饱满，不要出格' },
  { id: 'YY-08', subj: 'YY', rarity: 'N', name: '跟读能手', art: '🎧🎤', know: '跟读三步骤：听、模仿、对比', task: '跟读一段英语音频', tip: '注意语音语调，不要平调' },
  { id: 'YY-09', subj: 'YY', rarity: 'R', name: '单词猎手', art: '🏹🦋', know: '单词分类：名词、动词、形容词', task: '积累10个新单词并造句', tip: '按主题记单词，比如食物、动物' },
  { id: 'YY-10', subj: 'YY', rarity: 'R', name: '句型法师', art: '🪄💬', know: '基本句型：This is... / I like... / Can you...?', task: '掌握并运用一个句型', tip: '句型要替换关键词多练几遍' },
  { id: 'YY-11', subj: 'YY', rarity: 'R', name: '对话行者', art: '🗨️🗯️', know: '情景对话：购物、问路、点餐', task: '完成一段情景对话', tip: '角色扮演，一人一句' },
  { id: 'YY-12', subj: 'YY', rarity: 'R', name: '阅读初探', art: '📖🐻', know: '阅读技巧：找关键词、猜词义、抓大意', task: '读懂一篇短文并答题', tip: '不认识的词先跳过，读完再猜' },
  { id: 'YY-13', subj: 'YY', rarity: 'R', name: '拼读达人', art: '🔤🧱', know: '自然拼读：cat, dog, bike, cake', task: '用自然拼读拼出新词', tip: '见词能读，听音能写' },
  { id: 'YY-14', subj: 'YY', rarity: 'R', name: '小翻译官', art: '🇨🇳⇄🇬🇧', know: '中英互译注意：语序、时态、习惯表达', task: '中英互译5个句子', tip: '翻译不要逐字，要通顺' },
  { id: 'YY-15', subj: 'YY', rarity: 'SR', name: '听力先锋', art: '👂〰️', know: '听力技巧：听前预测、听关键词、抓主旨', task: '听力测试全对', tip: '听不清的地方不要纠结，继续往下听' },
  { id: 'YY-16', subj: 'YY', rarity: 'SR', name: '口语新星', art: '👄🌟', know: '口语表达：发音、语调、流利度', task: '完成一次英语演讲/表演', tip: '大声说，不怕错' },
  { id: 'YY-17', subj: 'YY', rarity: 'SR', name: '阅读王者', art: '👑📘', know: '英文阅读：绘本、分级读物、章节书', task: '读完一本英文绘本并复述', tip: '从简单的开始，每天读一点' },
  { id: 'YY-18', subj: 'YY', rarity: 'SR', name: '写作小匠', art: '✒️📄', know: '英语写作：开头、正文、结尾', task: '完成一篇英语小短文', tip: '先写简单句，再慢慢加修饰' },
  { id: 'YY-19', subj: 'YY', rarity: 'SSR', name: '英语宗师', art: '🎩🗽', know: '英语综合能力：听说读写', task: '期中/期末英语成绩优异', tip: '英语靠坚持，每天听读说' },
  { id: 'YY-20', subj: 'YY', rarity: 'SSR', name: '小小外交官', art: '🧑‍💼🌍', know: '英语竞赛常见题型：听力、口语、阅读、写作', task: '校级英语竞赛获奖', tip: '赛前多模拟，自信表达' },

  // ---------------- UR 限定卡 ----------------
  { id: 'UR-01', subj: 'UR', rarity: 'UR', name: '三科全能王', art: '🏆🧒🌟', know: '语文=理解与表达，数学=逻辑与运算，英语=交流与视野', task: '三科全面发展，不偏科', tip: '每天每科都碰一碰，日积月累全能王',
    quote: '语文让你会表达，数学让你会思考，英语让你看世界。三科全能，未来无限。' },
];
